Update check_labels.yml

diff --git a/.github/workflows/check_labels.yml b/.github/workflows/check_labels.yml
--- a/.github/workflows/check_labels.yml
+++ b/.github/workflows/check_labels.yml
@@ -11,16 +11,20 @@ jobs:
   check-labels:
     runs-on: ubuntu-latest
     steps:
-      - name: Check for "type:" label
-        run: |
-          # Convert labels to JSON and extract names
+      - run: |
           labels=$(echo '${{ toJson(github.event.pull_request.labels) }}' | jq -r '.[].name')
-          echo "Labels Array: $labels"
-
-          # Check for "type:" label
           if echo "$labels" | grep -q '^type:'; then
             echo "Found a 'type:' label."
           else
             echo "Error: No 'type:' label found."
+            exit 1
+          fi
+
+      - run: |
+          labels=$(echo '${{ toJson(github.event.pull_request.labels) }}' | jq -r '.[].name')
+          if echo "$labels" | grep -q '^status:'; then
+            echo "Found a 'status:' label."
+          else
+            echo "Error: No 'status:' label found."
             exit 1
           fi
